version: '3.8'

services:
  api:
    build: ./api
    container_name: golang_api
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["go", "run", "."]
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    build: ./front
    container_name: react_front
    volumes:
      - ./front:/app
    working_dir: /app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
