POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "    Berisberto     ",
  "email": "empdsadsaddresa@asda.ds   ",
  "senha": "123456",
  "setor_id": "3cb91849-eb10-4967-8c73-325f2bec3fd4",
  "tipo": "admin"
}

### busca usuarios
GET http://localhost:8080/usuarios

### busca usuario
GET http://localhost:8080/usuarios/42205080-3223-4f33-acd5-d08040a5b475

### Update usuario
PUT http://localhost:8080/usuarios/42205080-3223-4f33-acd5-d08040a5b475
Content-Type: application/json

{
  "nome": "    Jorge     ",
  "email": "matheus@empresa.com   ",
  "setor_id": "3cb91849-eb10-4967-8c73-325f2bec3fd4",
  "tipo": "admin"
}

### busca usuario
DELETE http://localhost:8080/usuarios/9020279c-da64-4995-b2d9-2debbf411cc4

# 3cb91849-eb10-4967-8c73-325f2bec3fd4 - setor banco work
# ID eae8b09b-51e6-4f81-8c18-2c8d06131891
# email thyago@empresa.com
# senha 123456

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "empdsadsaddresa@ada.ds",
  "senha": "123456"
}



